### PR TITLE
[PWPA-2216] Add prefix for cement and formation materials;

### PR DESCRIPTION
**Pull request by gabrielantao**
Add prefix for cement `CM_` and for formation `FC_` because it's needed for APB plugin in order to identify these materials for calculations.

PWPA-2216

### CODE REVIEW

**Review by noliveiraesss — APPROVED** [review]
🔝

**Review by noliveiraesss — APPROVED** [review]

**Review by carlosnewmar — APPROVED** [review]
OK, it seems a good plan for the ALFAsim x SCORE integration.
But, as I mentioned in the other PR, those material can have any name. For a generic solution, perhaps we need to improve it. We can consider ir in another moment.

Can you create a task? pls

**Comment by noliveiraesss** [comment]
@carlosnewmar [PWPA-2217]

[PWPA-2217]: https://esss.atlassian.net/browse/PWPA-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by ckiyono — APPROVED** [review]

**Comment by gabrielantao** [comment]
> We can consider ir in another moment.

Yeah, this just a temporary solution, but we can iterate to improve this solution.

**Pull request merged**
